{
	"version": 1596110837,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/card-sheet0.png",
		"images/card-sheet1.png",
		"images/fundo.png",
		"images/memoriaformas-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnsom-sheet0.png",
		"images/btnsom-sheet1.png",
		"images/btnmenu-sheet0.png",
		"images/texttime.png",
		"images/particula1.png",
		"images/particula2.png",
		"images/credits-sheet0.png",
		"images/btnexit-sheet0.png",
		"images/spfnomejogo.png",
		"images/card2-sheet0.png",
		"images/card2-sheet1.png",
		"images/spftitulo.png",
		"images/spfforma.png",
		"images/btnconferir-sheet0.png",
		"images/spfconferir.png",
		"images/sptcheck1-sheet0.png",
		"images/sptcheck1-sheet1.png",
		"images/sptcheck2-sheet0.png",
		"images/sptcheckmedal-sheet0.png",
		"images/spfnivelconcluido.png",
		"images/background-sheet0.png",
		"images/sptfundotitulo-sheet0.png",
		"images/sprtrofeu-sheet0.png",
		"media/amarelo (mp3cut.net).ogg",
		"media/azul (mp3cut.net).ogg",
		"media/circular (mp3cut.net).ogg",
		"media/circulo (mp3cut.net).ogg",
		"media/escolha-um (mp3cut.net).ogg",
		"media/escolha-um-objeto (mp3cut.net).ogg",
		"media/quadrado (mp3cut.net).ogg",
		"media/retangular (mp3cut.net).ogg",
		"media/retangulo (mp3cut.net).ogg",
		"media/triangular (mp3cut.net).ogg",
		"media/triangulo (mp3cut.net).ogg",
		"media/vermelho (mp3cut.net).ogg",
		"media/click1.ogg",
		"media/cardopenpackage2.ogg",
		"media/cardplace1.ogg",
		"media/jingles_steel00.ogg",
		"media/applause.ogg",
		"media/muito_bem (mp3cut.net).ogg",
		"media/nao-nao (mp3cut.net).ogg",
		"media/parabéns (mp3cut.net).ogg",
		"media/user6965013668010241 - nivel-concluido (mastered) (online-audio-converter.com).ogg",
		"media/376318__jimhancock__tada.ogg",
		"media/resposta-certa (online-audio-converter.com).ogg",
		"media/resposta-errada (online-audio-converter.com).ogg",
		"media/e-isso-ai-parabens (mp3cut.net).ogg",
		"media/bensound-smile (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"tabela-atividade-formas-objetos.json"
	]
}